// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: agent.proto

package agentv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReportRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ClusterId        string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	ClusterName      string                 `protobuf:"bytes,2,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	NodeName         string                 `protobuf:"bytes,3,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	AgentId          string                 `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Version          string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	TimestampSeconds int64                  `protobuf:"varint,6,opt,name=timestamp_seconds,json=timestampSeconds,proto3" json:"timestamp_seconds,omitempty"`
	Snapshot         *Snapshot              `protobuf:"bytes,7,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReportRequest) Reset() {
	*x = ReportRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportRequest) ProtoMessage() {}

func (x *ReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportRequest.ProtoReflect.Descriptor instead.
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ReportRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ReportRequest) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *ReportRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *ReportRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ReportRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ReportRequest) GetTimestampSeconds() int64 {
	if x != nil {
		return x.TimestampSeconds
	}
	return 0
}

func (x *ReportRequest) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type ReportBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reports       []*ReportRequest       `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportBatchRequest) Reset() {
	*x = ReportBatchRequest{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportBatchRequest) ProtoMessage() {}

func (x *ReportBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportBatchRequest.ProtoReflect.Descriptor instead.
func (*ReportBatchRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ReportBatchRequest) GetReports() []*ReportRequest {
	if x != nil {
		return x.Reports
	}
	return nil
}

type ReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportResponse) Reset() {
	*x = ReportResponse{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportResponse) ProtoMessage() {}

func (x *ReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportResponse.ProtoReflect.Descriptor instead.
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ReportResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ReportResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type Snapshot struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TimestampSeconds int64                  `protobuf:"varint,1,opt,name=timestamp_seconds,json=timestampSeconds,proto3" json:"timestamp_seconds,omitempty"`
	Namespaces       []*NamespaceCostRecord `protobuf:"bytes,2,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	Nodes            []*NodeCostRecord      `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Resources        *ResourceSnapshot      `protobuf:"bytes,4,opt,name=resources,proto3" json:"resources,omitempty"`
	Network          *NetworkSnapshot       `protobuf:"bytes,5,opt,name=network,proto3" json:"network,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *Snapshot) GetTimestampSeconds() int64 {
	if x != nil {
		return x.TimestampSeconds
	}
	return 0
}

func (x *Snapshot) GetNamespaces() []*NamespaceCostRecord {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *Snapshot) GetNodes() []*NodeCostRecord {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *Snapshot) GetResources() *ResourceSnapshot {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *Snapshot) GetNetwork() *NetworkSnapshot {
	if x != nil {
		return x.Network
	}
	return nil
}

type NamespaceCostRecord struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ClusterId          string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Namespace          string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Labels             map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Environment        string                 `protobuf:"bytes,4,opt,name=environment,proto3" json:"environment,omitempty"`
	CpuRequestMilli    int64                  `protobuf:"varint,5,opt,name=cpu_request_milli,json=cpuRequestMilli,proto3" json:"cpu_request_milli,omitempty"`
	CpuUsageMilli      int64                  `protobuf:"varint,6,opt,name=cpu_usage_milli,json=cpuUsageMilli,proto3" json:"cpu_usage_milli,omitempty"`
	MemoryRequestBytes int64                  `protobuf:"varint,7,opt,name=memory_request_bytes,json=memoryRequestBytes,proto3" json:"memory_request_bytes,omitempty"`
	MemoryUsageBytes   int64                  `protobuf:"varint,8,opt,name=memory_usage_bytes,json=memoryUsageBytes,proto3" json:"memory_usage_bytes,omitempty"`
	PodCount           int64                  `protobuf:"varint,9,opt,name=pod_count,json=podCount,proto3" json:"pod_count,omitempty"`
	HourlyCost         float64                `protobuf:"fixed64,10,opt,name=hourly_cost,json=hourlyCost,proto3" json:"hourly_cost,omitempty"`
	NetworkTxBytes     uint64                 `protobuf:"varint,11,opt,name=network_tx_bytes,json=networkTxBytes,proto3" json:"network_tx_bytes,omitempty"`
	NetworkRxBytes     uint64                 `protobuf:"varint,12,opt,name=network_rx_bytes,json=networkRxBytes,proto3" json:"network_rx_bytes,omitempty"`
	NetworkEgressCost  float64                `protobuf:"fixed64,13,opt,name=network_egress_cost,json=networkEgressCost,proto3" json:"network_egress_cost,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *NamespaceCostRecord) Reset() {
	*x = NamespaceCostRecord{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceCostRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceCostRecord) ProtoMessage() {}

func (x *NamespaceCostRecord) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceCostRecord.ProtoReflect.Descriptor instead.
func (*NamespaceCostRecord) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *NamespaceCostRecord) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *NamespaceCostRecord) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *NamespaceCostRecord) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *NamespaceCostRecord) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *NamespaceCostRecord) GetCpuRequestMilli() int64 {
	if x != nil {
		return x.CpuRequestMilli
	}
	return 0
}

func (x *NamespaceCostRecord) GetCpuUsageMilli() int64 {
	if x != nil {
		return x.CpuUsageMilli
	}
	return 0
}

func (x *NamespaceCostRecord) GetMemoryRequestBytes() int64 {
	if x != nil {
		return x.MemoryRequestBytes
	}
	return 0
}

func (x *NamespaceCostRecord) GetMemoryUsageBytes() int64 {
	if x != nil {
		return x.MemoryUsageBytes
	}
	return 0
}

func (x *NamespaceCostRecord) GetPodCount() int64 {
	if x != nil {
		return x.PodCount
	}
	return 0
}

func (x *NamespaceCostRecord) GetHourlyCost() float64 {
	if x != nil {
		return x.HourlyCost
	}
	return 0
}

func (x *NamespaceCostRecord) GetNetworkTxBytes() uint64 {
	if x != nil {
		return x.NetworkTxBytes
	}
	return 0
}

func (x *NamespaceCostRecord) GetNetworkRxBytes() uint64 {
	if x != nil {
		return x.NetworkRxBytes
	}
	return 0
}

func (x *NamespaceCostRecord) GetNetworkEgressCost() float64 {
	if x != nil {
		return x.NetworkEgressCost
	}
	return 0
}

type NodeCostRecord struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ClusterId              string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	NodeName               string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	CpuAllocatableMilli    int64                  `protobuf:"varint,3,opt,name=cpu_allocatable_milli,json=cpuAllocatableMilli,proto3" json:"cpu_allocatable_milli,omitempty"`
	MemoryAllocatableBytes int64                  `protobuf:"varint,4,opt,name=memory_allocatable_bytes,json=memoryAllocatableBytes,proto3" json:"memory_allocatable_bytes,omitempty"`
	Labels                 map[string]string      `protobuf:"bytes,5,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Taints                 []string               `protobuf:"bytes,6,rep,name=taints,proto3" json:"taints,omitempty"`
	InstanceType           string                 `protobuf:"bytes,7,opt,name=instance_type,json=instanceType,proto3" json:"instance_type,omitempty"`
	Status                 string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	IsUnderPressure        bool                   `protobuf:"varint,9,opt,name=is_under_pressure,json=isUnderPressure,proto3" json:"is_under_pressure,omitempty"`
	HourlyCost             float64                `protobuf:"fixed64,10,opt,name=hourly_cost,json=hourlyCost,proto3" json:"hourly_cost,omitempty"`
	CpuUsagePercent        float64                `protobuf:"fixed64,11,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	MemoryUsagePercent     float64                `protobuf:"fixed64,12,opt,name=memory_usage_percent,json=memoryUsagePercent,proto3" json:"memory_usage_percent,omitempty"`
	PodCount               int64                  `protobuf:"varint,13,opt,name=pod_count,json=podCount,proto3" json:"pod_count,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *NodeCostRecord) Reset() {
	*x = NodeCostRecord{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeCostRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeCostRecord) ProtoMessage() {}

func (x *NodeCostRecord) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeCostRecord.ProtoReflect.Descriptor instead.
func (*NodeCostRecord) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *NodeCostRecord) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *NodeCostRecord) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *NodeCostRecord) GetCpuAllocatableMilli() int64 {
	if x != nil {
		return x.CpuAllocatableMilli
	}
	return 0
}

func (x *NodeCostRecord) GetMemoryAllocatableBytes() int64 {
	if x != nil {
		return x.MemoryAllocatableBytes
	}
	return 0
}

func (x *NodeCostRecord) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *NodeCostRecord) GetTaints() []string {
	if x != nil {
		return x.Taints
	}
	return nil
}

func (x *NodeCostRecord) GetInstanceType() string {
	if x != nil {
		return x.InstanceType
	}
	return ""
}

func (x *NodeCostRecord) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NodeCostRecord) GetIsUnderPressure() bool {
	if x != nil {
		return x.IsUnderPressure
	}
	return false
}

func (x *NodeCostRecord) GetHourlyCost() float64 {
	if x != nil {
		return x.HourlyCost
	}
	return 0
}

func (x *NodeCostRecord) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

func (x *NodeCostRecord) GetMemoryUsagePercent() float64 {
	if x != nil {
		return x.MemoryUsagePercent
	}
	return 0
}

func (x *NodeCostRecord) GetPodCount() int64 {
	if x != nil {
		return x.PodCount
	}
	return 0
}

type ResourceSnapshot struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ClusterId               string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	CpuUsageMilliTotal      int64                  `protobuf:"varint,2,opt,name=cpu_usage_milli_total,json=cpuUsageMilliTotal,proto3" json:"cpu_usage_milli_total,omitempty"`
	CpuRequestMilliTotal    int64                  `protobuf:"varint,3,opt,name=cpu_request_milli_total,json=cpuRequestMilliTotal,proto3" json:"cpu_request_milli_total,omitempty"`
	MemoryUsageBytesTotal   int64                  `protobuf:"varint,4,opt,name=memory_usage_bytes_total,json=memoryUsageBytesTotal,proto3" json:"memory_usage_bytes_total,omitempty"`
	MemoryRequestBytesTotal int64                  `protobuf:"varint,5,opt,name=memory_request_bytes_total,json=memoryRequestBytesTotal,proto3" json:"memory_request_bytes_total,omitempty"`
	TotalNodeHourlyCost     float64                `protobuf:"fixed64,6,opt,name=total_node_hourly_cost,json=totalNodeHourlyCost,proto3" json:"total_node_hourly_cost,omitempty"`
	NetworkTxBytesTotal     uint64                 `protobuf:"varint,7,opt,name=network_tx_bytes_total,json=networkTxBytesTotal,proto3" json:"network_tx_bytes_total,omitempty"`
	NetworkRxBytesTotal     uint64                 `protobuf:"varint,8,opt,name=network_rx_bytes_total,json=networkRxBytesTotal,proto3" json:"network_rx_bytes_total,omitempty"`
	NetworkEgressCostTotal  float64                `protobuf:"fixed64,9,opt,name=network_egress_cost_total,json=networkEgressCostTotal,proto3" json:"network_egress_cost_total,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ResourceSnapshot) Reset() {
	*x = ResourceSnapshot{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceSnapshot) ProtoMessage() {}

func (x *ResourceSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceSnapshot.ProtoReflect.Descriptor instead.
func (*ResourceSnapshot) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ResourceSnapshot) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ResourceSnapshot) GetCpuUsageMilliTotal() int64 {
	if x != nil {
		return x.CpuUsageMilliTotal
	}
	return 0
}

func (x *ResourceSnapshot) GetCpuRequestMilliTotal() int64 {
	if x != nil {
		return x.CpuRequestMilliTotal
	}
	return 0
}

func (x *ResourceSnapshot) GetMemoryUsageBytesTotal() int64 {
	if x != nil {
		return x.MemoryUsageBytesTotal
	}
	return 0
}

func (x *ResourceSnapshot) GetMemoryRequestBytesTotal() int64 {
	if x != nil {
		return x.MemoryRequestBytesTotal
	}
	return 0
}

func (x *ResourceSnapshot) GetTotalNodeHourlyCost() float64 {
	if x != nil {
		return x.TotalNodeHourlyCost
	}
	return 0
}

func (x *ResourceSnapshot) GetNetworkTxBytesTotal() uint64 {
	if x != nil {
		return x.NetworkTxBytesTotal
	}
	return 0
}

func (x *ResourceSnapshot) GetNetworkRxBytesTotal() uint64 {
	if x != nil {
		return x.NetworkRxBytesTotal
	}
	return 0
}

func (x *ResourceSnapshot) GetNetworkEgressCostTotal() float64 {
	if x != nil {
		return x.NetworkEgressCostTotal
	}
	return 0
}

type NetworkSnapshot struct {
	state      protoimpl.MessageState    `protogen:"open.v1"`
	ClusterId  string                    `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	TxBytes    uint64                    `protobuf:"varint,2,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	RxBytes    uint64                    `protobuf:"varint,3,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	EgressCost float64                   `protobuf:"fixed64,4,opt,name=egress_cost,json=egressCost,proto3" json:"egress_cost,omitempty"`
	ByClass    []*NetworkClassTotals     `protobuf:"bytes,5,rep,name=by_class,json=byClass,proto3" json:"by_class,omitempty"`
	Pods       []*PodNetworkRecord       `protobuf:"bytes,6,rep,name=pods,proto3" json:"pods,omitempty"`
	Namespaces []*NamespaceNetworkRecord `protobuf:"bytes,7,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	// Detailed connection graphs (optional/feature-flagged)
	PodConnections       []*NetworkConnection `protobuf:"bytes,8,rep,name=pod_connections,json=podConnections,proto3" json:"pod_connections,omitempty"`
	WorkloadConnections  []*NetworkConnection `protobuf:"bytes,9,rep,name=workload_connections,json=workloadConnections,proto3" json:"workload_connections,omitempty"`
	NamespaceConnections []*NetworkConnection `protobuf:"bytes,10,rep,name=namespace_connections,json=namespaceConnections,proto3" json:"namespace_connections,omitempty"`
	ServiceConnections   []*NetworkConnection `protobuf:"bytes,11,rep,name=service_connections,json=serviceConnections,proto3" json:"service_connections,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NetworkSnapshot) Reset() {
	*x = NetworkSnapshot{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkSnapshot) ProtoMessage() {}

func (x *NetworkSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkSnapshot.ProtoReflect.Descriptor instead.
func (*NetworkSnapshot) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *NetworkSnapshot) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *NetworkSnapshot) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *NetworkSnapshot) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *NetworkSnapshot) GetEgressCost() float64 {
	if x != nil {
		return x.EgressCost
	}
	return 0
}

func (x *NetworkSnapshot) GetByClass() []*NetworkClassTotals {
	if x != nil {
		return x.ByClass
	}
	return nil
}

func (x *NetworkSnapshot) GetPods() []*PodNetworkRecord {
	if x != nil {
		return x.Pods
	}
	return nil
}

func (x *NetworkSnapshot) GetNamespaces() []*NamespaceNetworkRecord {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

func (x *NetworkSnapshot) GetPodConnections() []*NetworkConnection {
	if x != nil {
		return x.PodConnections
	}
	return nil
}

func (x *NetworkSnapshot) GetWorkloadConnections() []*NetworkConnection {
	if x != nil {
		return x.WorkloadConnections
	}
	return nil
}

func (x *NetworkSnapshot) GetNamespaceConnections() []*NetworkConnection {
	if x != nil {
		return x.NamespaceConnections
	}
	return nil
}

func (x *NetworkSnapshot) GetServiceConnections() []*NetworkConnection {
	if x != nil {
		return x.ServiceConnections
	}
	return nil
}

type NetworkClassTotals struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Class            string                 `protobuf:"bytes,1,opt,name=class,proto3" json:"class,omitempty"`
	TxBytes          uint64                 `protobuf:"varint,2,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	RxBytes          uint64                 `protobuf:"varint,3,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	EgressCostHourly float64                `protobuf:"fixed64,4,opt,name=egress_cost_hourly,json=egressCostHourly,proto3" json:"egress_cost_hourly,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NetworkClassTotals) Reset() {
	*x = NetworkClassTotals{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkClassTotals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkClassTotals) ProtoMessage() {}

func (x *NetworkClassTotals) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkClassTotals.ProtoReflect.Descriptor instead.
func (*NetworkClassTotals) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *NetworkClassTotals) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *NetworkClassTotals) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *NetworkClassTotals) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *NetworkClassTotals) GetEgressCostHourly() float64 {
	if x != nil {
		return x.EgressCostHourly
	}
	return 0
}

type PodNetworkRecord struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Namespace        string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Pod              string                 `protobuf:"bytes,2,opt,name=pod,proto3" json:"pod,omitempty"`
	Node             string                 `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	TxBytes          uint64                 `protobuf:"varint,4,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	RxBytes          uint64                 `protobuf:"varint,5,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	EgressCostHourly float64                `protobuf:"fixed64,6,opt,name=egress_cost_hourly,json=egressCostHourly,proto3" json:"egress_cost_hourly,omitempty"`
	ByClass          []*NetworkClassTotals  `protobuf:"bytes,7,rep,name=by_class,json=byClass,proto3" json:"by_class,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PodNetworkRecord) Reset() {
	*x = PodNetworkRecord{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodNetworkRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodNetworkRecord) ProtoMessage() {}

func (x *PodNetworkRecord) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodNetworkRecord.ProtoReflect.Descriptor instead.
func (*PodNetworkRecord) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *PodNetworkRecord) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PodNetworkRecord) GetPod() string {
	if x != nil {
		return x.Pod
	}
	return ""
}

func (x *PodNetworkRecord) GetNode() string {
	if x != nil {
		return x.Node
	}
	return ""
}

func (x *PodNetworkRecord) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *PodNetworkRecord) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *PodNetworkRecord) GetEgressCostHourly() float64 {
	if x != nil {
		return x.EgressCostHourly
	}
	return 0
}

func (x *PodNetworkRecord) GetByClass() []*NetworkClassTotals {
	if x != nil {
		return x.ByClass
	}
	return nil
}

type NamespaceNetworkRecord struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Namespace        string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TxBytes          uint64                 `protobuf:"varint,2,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	RxBytes          uint64                 `protobuf:"varint,3,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	EgressCostHourly float64                `protobuf:"fixed64,4,opt,name=egress_cost_hourly,json=egressCostHourly,proto3" json:"egress_cost_hourly,omitempty"`
	ByClass          []*NetworkClassTotals  `protobuf:"bytes,5,rep,name=by_class,json=byClass,proto3" json:"by_class,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NamespaceNetworkRecord) Reset() {
	*x = NamespaceNetworkRecord{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceNetworkRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceNetworkRecord) ProtoMessage() {}

func (x *NamespaceNetworkRecord) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceNetworkRecord.ProtoReflect.Descriptor instead.
func (*NamespaceNetworkRecord) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *NamespaceNetworkRecord) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *NamespaceNetworkRecord) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *NamespaceNetworkRecord) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *NamespaceNetworkRecord) GetEgressCostHourly() float64 {
	if x != nil {
		return x.EgressCostHourly
	}
	return 0
}

func (x *NamespaceNetworkRecord) GetByClass() []*NetworkClassTotals {
	if x != nil {
		return x.ByClass
	}
	return nil
}

type NetworkConnection struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Source           *NetworkEndpoint       `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination      *NetworkEndpoint       `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
	Class            string                 `protobuf:"bytes,3,opt,name=class,proto3" json:"class,omitempty"`
	TxBytes          uint64                 `protobuf:"varint,4,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	RxBytes          uint64                 `protobuf:"varint,5,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	EgressCostHourly float64                `protobuf:"fixed64,6,opt,name=egress_cost_hourly,json=egressCostHourly,proto3" json:"egress_cost_hourly,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *NetworkConnection) Reset() {
	*x = NetworkConnection{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConnection) ProtoMessage() {}

func (x *NetworkConnection) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConnection.ProtoReflect.Descriptor instead.
func (*NetworkConnection) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *NetworkConnection) GetSource() *NetworkEndpoint {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *NetworkConnection) GetDestination() *NetworkEndpoint {
	if x != nil {
		return x.Destination
	}
	return nil
}

func (x *NetworkConnection) GetClass() string {
	if x != nil {
		return x.Class
	}
	return ""
}

func (x *NetworkConnection) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *NetworkConnection) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *NetworkConnection) GetEgressCostHourly() float64 {
	if x != nil {
		return x.EgressCostHourly
	}
	return 0
}

type NetworkEndpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkEndpoint) Reset() {
	*x = NetworkEndpoint{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkEndpoint) ProtoMessage() {}

func (x *NetworkEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkEndpoint.ProtoReflect.Descriptor instead.
func (*NetworkEndpoint) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *NetworkEndpoint) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *NetworkEndpoint) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *NetworkEndpoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\bagent.v1\"\x80\x02\n" +
	"\rReportRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12!\n" +
	"\fcluster_name\x18\x02 \x01(\tR\vclusterName\x12\x1b\n" +
	"\tnode_name\x18\x03 \x01(\tR\bnodeName\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12+\n" +
	"\x11timestamp_seconds\x18\x06 \x01(\x03R\x10timestampSeconds\x12.\n" +
	"\bsnapshot\x18\a \x01(\v2\x12.agent.v1.SnapshotR\bsnapshot\"G\n" +
	"\x12ReportBatchRequest\x121\n" +
	"\areports\x18\x01 \x03(\v2\x17.agent.v1.ReportRequestR\areports\"Q\n" +
	"\x0eReportResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x95\x02\n" +
	"\bSnapshot\x12+\n" +
	"\x11timestamp_seconds\x18\x01 \x01(\x03R\x10timestampSeconds\x12=\n" +
	"\n" +
	"namespaces\x18\x02 \x03(\v2\x1d.agent.v1.NamespaceCostRecordR\n" +
	"namespaces\x12.\n" +
	"\x05nodes\x18\x03 \x03(\v2\x18.agent.v1.NodeCostRecordR\x05nodes\x128\n" +
	"\tresources\x18\x04 \x01(\v2\x1a.agent.v1.ResourceSnapshotR\tresources\x123\n" +
	"\anetwork\x18\x05 \x01(\v2\x19.agent.v1.NetworkSnapshotR\anetwork\"\xe8\x04\n" +
	"\x13NamespaceCostRecord\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12A\n" +
	"\x06labels\x18\x03 \x03(\v2).agent.v1.NamespaceCostRecord.LabelsEntryR\x06labels\x12 \n" +
	"\venvironment\x18\x04 \x01(\tR\venvironment\x12*\n" +
	"\x11cpu_request_milli\x18\x05 \x01(\x03R\x0fcpuRequestMilli\x12&\n" +
	"\x0fcpu_usage_milli\x18\x06 \x01(\x03R\rcpuUsageMilli\x120\n" +
	"\x14memory_request_bytes\x18\a \x01(\x03R\x12memoryRequestBytes\x12,\n" +
	"\x12memory_usage_bytes\x18\b \x01(\x03R\x10memoryUsageBytes\x12\x1b\n" +
	"\tpod_count\x18\t \x01(\x03R\bpodCount\x12\x1f\n" +
	"\vhourly_cost\x18\n" +
	" \x01(\x01R\n" +
	"hourlyCost\x12(\n" +
	"\x10network_tx_bytes\x18\v \x01(\x04R\x0enetworkTxBytes\x12(\n" +
	"\x10network_rx_bytes\x18\f \x01(\x04R\x0enetworkRxBytes\x12.\n" +
	"\x13network_egress_cost\x18\r \x01(\x01R\x11networkEgressCost\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd0\x04\n" +
	"\x0eNodeCostRecord\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x122\n" +
	"\x15cpu_allocatable_milli\x18\x03 \x01(\x03R\x13cpuAllocatableMilli\x128\n" +
	"\x18memory_allocatable_bytes\x18\x04 \x01(\x03R\x16memoryAllocatableBytes\x12<\n" +
	"\x06labels\x18\x05 \x03(\v2$.agent.v1.NodeCostRecord.LabelsEntryR\x06labels\x12\x16\n" +
	"\x06taints\x18\x06 \x03(\tR\x06taints\x12#\n" +
	"\rinstance_type\x18\a \x01(\tR\finstanceType\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12*\n" +
	"\x11is_under_pressure\x18\t \x01(\bR\x0fisUnderPressure\x12\x1f\n" +
	"\vhourly_cost\x18\n" +
	" \x01(\x01R\n" +
	"hourlyCost\x12*\n" +
	"\x11cpu_usage_percent\x18\v \x01(\x01R\x0fcpuUsagePercent\x120\n" +
	"\x14memory_usage_percent\x18\f \x01(\x01R\x12memoryUsagePercent\x12\x1b\n" +
	"\tpod_count\x18\r \x01(\x03R\bpodCount\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xeb\x03\n" +
	"\x10ResourceSnapshot\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x121\n" +
	"\x15cpu_usage_milli_total\x18\x02 \x01(\x03R\x12cpuUsageMilliTotal\x125\n" +
	"\x17cpu_request_milli_total\x18\x03 \x01(\x03R\x14cpuRequestMilliTotal\x127\n" +
	"\x18memory_usage_bytes_total\x18\x04 \x01(\x03R\x15memoryUsageBytesTotal\x12;\n" +
	"\x1amemory_request_bytes_total\x18\x05 \x01(\x03R\x17memoryRequestBytesTotal\x123\n" +
	"\x16total_node_hourly_cost\x18\x06 \x01(\x01R\x13totalNodeHourlyCost\x123\n" +
	"\x16network_tx_bytes_total\x18\a \x01(\x04R\x13networkTxBytesTotal\x123\n" +
	"\x16network_rx_bytes_total\x18\b \x01(\x04R\x13networkRxBytesTotal\x129\n" +
	"\x19network_egress_cost_total\x18\t \x01(\x01R\x16networkEgressCostTotal\"\xe8\x04\n" +
	"\x0fNetworkSnapshot\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x19\n" +
	"\btx_bytes\x18\x02 \x01(\x04R\atxBytes\x12\x19\n" +
	"\brx_bytes\x18\x03 \x01(\x04R\arxBytes\x12\x1f\n" +
	"\vegress_cost\x18\x04 \x01(\x01R\n" +
	"egressCost\x127\n" +
	"\bby_class\x18\x05 \x03(\v2\x1c.agent.v1.NetworkClassTotalsR\abyClass\x12.\n" +
	"\x04pods\x18\x06 \x03(\v2\x1a.agent.v1.PodNetworkRecordR\x04pods\x12@\n" +
	"\n" +
	"namespaces\x18\a \x03(\v2 .agent.v1.NamespaceNetworkRecordR\n" +
	"namespaces\x12D\n" +
	"\x0fpod_connections\x18\b \x03(\v2\x1b.agent.v1.NetworkConnectionR\x0epodConnections\x12N\n" +
	"\x14workload_connections\x18\t \x03(\v2\x1b.agent.v1.NetworkConnectionR\x13workloadConnections\x12P\n" +
	"\x15namespace_connections\x18\n" +
	" \x03(\v2\x1b.agent.v1.NetworkConnectionR\x14namespaceConnections\x12L\n" +
	"\x13service_connections\x18\v \x03(\v2\x1b.agent.v1.NetworkConnectionR\x12serviceConnections\"\x8e\x01\n" +
	"\x12NetworkClassTotals\x12\x14\n" +
	"\x05class\x18\x01 \x01(\tR\x05class\x12\x19\n" +
	"\btx_bytes\x18\x02 \x01(\x04R\atxBytes\x12\x19\n" +
	"\brx_bytes\x18\x03 \x01(\x04R\arxBytes\x12,\n" +
	"\x12egress_cost_hourly\x18\x04 \x01(\x01R\x10egressCostHourly\"\xf3\x01\n" +
	"\x10PodNetworkRecord\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03pod\x18\x02 \x01(\tR\x03pod\x12\x12\n" +
	"\x04node\x18\x03 \x01(\tR\x04node\x12\x19\n" +
	"\btx_bytes\x18\x04 \x01(\x04R\atxBytes\x12\x19\n" +
	"\brx_bytes\x18\x05 \x01(\x04R\arxBytes\x12,\n" +
	"\x12egress_cost_hourly\x18\x06 \x01(\x01R\x10egressCostHourly\x127\n" +
	"\bby_class\x18\a \x03(\v2\x1c.agent.v1.NetworkClassTotalsR\abyClass\"\xd3\x01\n" +
	"\x16NamespaceNetworkRecord\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x19\n" +
	"\btx_bytes\x18\x02 \x01(\x04R\atxBytes\x12\x19\n" +
	"\brx_bytes\x18\x03 \x01(\x04R\arxBytes\x12,\n" +
	"\x12egress_cost_hourly\x18\x04 \x01(\x01R\x10egressCostHourly\x127\n" +
	"\bby_class\x18\x05 \x03(\v2\x1c.agent.v1.NetworkClassTotalsR\abyClass\"\xfd\x01\n" +
	"\x11NetworkConnection\x121\n" +
	"\x06source\x18\x01 \x01(\v2\x19.agent.v1.NetworkEndpointR\x06source\x12;\n" +
	"\vdestination\x18\x02 \x01(\v2\x19.agent.v1.NetworkEndpointR\vdestination\x12\x14\n" +
	"\x05class\x18\x03 \x01(\tR\x05class\x12\x19\n" +
	"\btx_bytes\x18\x04 \x01(\x04R\atxBytes\x12\x19\n" +
	"\brx_bytes\x18\x05 \x01(\x04R\arxBytes\x12,\n" +
	"\x12egress_cost_hourly\x18\x06 \x01(\x01R\x10egressCostHourly\"W\n" +
	"\x0fNetworkEndpoint\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name2\x8f\x01\n" +
	"\tCollector\x12;\n" +
	"\x06Report\x12\x17.agent.v1.ReportRequest\x1a\x18.agent.v1.ReportResponse\x12E\n" +
	"\vReportBatch\x12\x1c.agent.v1.ReportBatchRequest\x1a\x18.agent.v1.ReportResponseB7Z5clustercost-agent-k8s/internal/proto/agent/v1;agentv1b\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_agent_proto_goTypes = []any{
	(*ReportRequest)(nil),          // 0: agent.v1.ReportRequest
	(*ReportBatchRequest)(nil),     // 1: agent.v1.ReportBatchRequest
	(*ReportResponse)(nil),         // 2: agent.v1.ReportResponse
	(*Snapshot)(nil),               // 3: agent.v1.Snapshot
	(*NamespaceCostRecord)(nil),    // 4: agent.v1.NamespaceCostRecord
	(*NodeCostRecord)(nil),         // 5: agent.v1.NodeCostRecord
	(*ResourceSnapshot)(nil),       // 6: agent.v1.ResourceSnapshot
	(*NetworkSnapshot)(nil),        // 7: agent.v1.NetworkSnapshot
	(*NetworkClassTotals)(nil),     // 8: agent.v1.NetworkClassTotals
	(*PodNetworkRecord)(nil),       // 9: agent.v1.PodNetworkRecord
	(*NamespaceNetworkRecord)(nil), // 10: agent.v1.NamespaceNetworkRecord
	(*NetworkConnection)(nil),      // 11: agent.v1.NetworkConnection
	(*NetworkEndpoint)(nil),        // 12: agent.v1.NetworkEndpoint
	nil,                            // 13: agent.v1.NamespaceCostRecord.LabelsEntry
	nil,                            // 14: agent.v1.NodeCostRecord.LabelsEntry
}
var file_agent_proto_depIdxs = []int32{
	3,  // 0: agent.v1.ReportRequest.snapshot:type_name -> agent.v1.Snapshot
	0,  // 1: agent.v1.ReportBatchRequest.reports:type_name -> agent.v1.ReportRequest
	4,  // 2: agent.v1.Snapshot.namespaces:type_name -> agent.v1.NamespaceCostRecord
	5,  // 3: agent.v1.Snapshot.nodes:type_name -> agent.v1.NodeCostRecord
	6,  // 4: agent.v1.Snapshot.resources:type_name -> agent.v1.ResourceSnapshot
	7,  // 5: agent.v1.Snapshot.network:type_name -> agent.v1.NetworkSnapshot
	13, // 6: agent.v1.NamespaceCostRecord.labels:type_name -> agent.v1.NamespaceCostRecord.LabelsEntry
	14, // 7: agent.v1.NodeCostRecord.labels:type_name -> agent.v1.NodeCostRecord.LabelsEntry
	8,  // 8: agent.v1.NetworkSnapshot.by_class:type_name -> agent.v1.NetworkClassTotals
	9,  // 9: agent.v1.NetworkSnapshot.pods:type_name -> agent.v1.PodNetworkRecord
	10, // 10: agent.v1.NetworkSnapshot.namespaces:type_name -> agent.v1.NamespaceNetworkRecord
	11, // 11: agent.v1.NetworkSnapshot.pod_connections:type_name -> agent.v1.NetworkConnection
	11, // 12: agent.v1.NetworkSnapshot.workload_connections:type_name -> agent.v1.NetworkConnection
	11, // 13: agent.v1.NetworkSnapshot.namespace_connections:type_name -> agent.v1.NetworkConnection
	11, // 14: agent.v1.NetworkSnapshot.service_connections:type_name -> agent.v1.NetworkConnection
	8,  // 15: agent.v1.PodNetworkRecord.by_class:type_name -> agent.v1.NetworkClassTotals
	8,  // 16: agent.v1.NamespaceNetworkRecord.by_class:type_name -> agent.v1.NetworkClassTotals
	12, // 17: agent.v1.NetworkConnection.source:type_name -> agent.v1.NetworkEndpoint
	12, // 18: agent.v1.NetworkConnection.destination:type_name -> agent.v1.NetworkEndpoint
	0,  // 19: agent.v1.Collector.Report:input_type -> agent.v1.ReportRequest
	1,  // 20: agent.v1.Collector.ReportBatch:input_type -> agent.v1.ReportBatchRequest
	2,  // 21: agent.v1.Collector.Report:output_type -> agent.v1.ReportResponse
	2,  // 22: agent.v1.Collector.ReportBatch:output_type -> agent.v1.ReportResponse
	21, // [21:23] is the sub-list for method output_type
	19, // [19:21] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
