run:
  timeout: 5m
  tests: false

linters:
  enable:
    - gofmt
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - misspell

issues:
  exclude-use-default: false
  max-same-issues: 0
  max-issues-per-linter: 0
